#!/bin/bash

trap "exit 1" TERM INT

# Quit if any function returns an non-zero status.
set -eE
set -o pipefail

echo
echo Command line: $0 "$@"

module reset >& /dev/null
script_home="`dirname $(readlink -f $0)`"
set +eE
source $script_home/venv/$LMOD_SYSTEM_NAME/bin/activate
# Force stdin, stdout and stderr to be totally unbuffered. 
# See https://unix.stackexchange.com/questions/182537/write-python-stdout-to-file-immediately
python -u $script_home/pbsacct_usage_report.py "$@"
status=$?
deactivate
set -eE
